name: smp-core
main: com.tejaslamba.smpcore.Main
version: 1.0.0
api-version: 1.21
softdepend: [ProtocolLib]
commands:
  smp:
    description: SMP core command
    usage: /smp [menu|reload]
    aliases: [smpcore]
permissions:
  smpcore.reload:
    description: Reload plugin configuration
    default: op
  smpcore.menu:
    description: Open settings menu
    default: op
